/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Lock__factory } from "./Lock__factory";
export { MyToken__factory } from "./MyToken__factory";
export { SimpleStorage__factory } from "./SimpleStorage__factory";
export { VeriDoc__factory } from "./VeriDoc__factory";
