export const VRC25_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function transferFrom(address from, address to, uint256 amount) returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function issuer() view returns (address)",
  "function estimateFee(uint256 value) view returns (uint256)",
  "function minFee() view returns (uint256)",
  "function setMinFee(uint256 newMinFee)",
  "event Fee(address indexed from, address indexed to, address indexed issuer, uint256 amount)",
];
