/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { MyToken } from "./MyToken";
export type { SimpleStorage } from "./SimpleStorage";
export type { VeriDoc } from "./VeriDoc";
